### PR TITLE
WiFiManagerParameter init() to protected from private

### PR DESCRIPTION
**Pull request by dontsovcmc**
Little feature to make possible children classes for easy custom parameters.
Example: https://github.com/dontsovcmc/waterius/blob/master/ESP8266/src/setup_ap.h

### CODE REVIEW

**Comment by tablatronix** [comment]
Hmm should we add an example or use case?

**Comment by dontsovcmc** [comment]
No, no. I show you my code as a reason of this changes. 
I can make pull request with example if needed.

**Comment by tablatronix** [comment]
Yeah if we can put something in the docs It might be useful.

**Comment by dontsovcmc** [comment]
You are welcome: https://github.com/dontsovcmc/WiFiManager/blob/waterius_development/examples/CustomParamsWithConfig/CustomParamsWithConfig.ino

**Comment by dontsovcmc** [comment]
debug log:
```
--- Miniterm on /dev/tty.SLAB_USBtoUART  9600,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

* * * FIRST START * * *

␒�␀␄�=S��Press setup button
3..2..1..Settings loaded //you can see random EEPROM first time
WORK
String param: 789012345678901234567890 
Float param: 0.00
Int param: 909456435
IP param: 55.56.57.48

* * * RESET * * *

␒`�␄�␝���Press setup button
3..2..1..Settings loaded
SETUP
*WM: [3] allocating params bytes: 20
*WM: [2] Added Parameter: str
*WM: [2] Added Parameter: float
*WM: [2] Added Parameter: int
*WM: [2] Added Parameter: ip
*WM: [3] WIFI station disconnect 
*WM: [3] WiFi station enable 
*WM: [2] Disabling STA 
*WM: [2] Enabling AP 
*WM: [1] StartAP with SSID:  ESP_2966e8
*WM: [2] AP has anonymous access! 
*WM: [1] AP IP address: 192.168.4.1
*WM: [3] setupConfigPortal 
*WM: [1] Starting Web Portal 
*WM: [3] dns server started with ip:  192.168.4.1
*WM: [2] HTTP server started 
*WM: [2] WiFi Scan ASYNC started 
*WM: [2] Config Portal Running, blocking, waiting for clients... 
*WM: [2] WiFi Scan ASYNC completed in 2234 ms
*WM: [2] WiFi Scan ASYNC found: 7
*WM: [2] NUM CLIENTS: 0 
*WM: [3] -> connectivitycheck.gstatic.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> clients3.google.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> clients3.google.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> connectivitycheck.gstatic.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> c.whatsapp.net 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> mini5.opera-mini.net 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> connectivitycheck.gstatic.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [2] <- HTTP Root 
*WM: [3] -> 192.168.4.1 
*WM: [3] lastconxresult: WL_IDLE_STATUS
*WM: [2] WiFi Scan ASYNC started 
*WM: [3] -> 192.168.4.1 
*WM: [3] -> connectivitycheck.gstatic.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> connectivitycheck.gstatic.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [2] <- HTTP Wifi 
*WM: [2] Scan is cached 50651 ms ago
*WM: [1] 7 networks found
*WM: [2] DUP AP: 
*WM: [2] DUP AP: 
*WM: [2] DUP AP: 
*WM: [2] DUP AP: 
*WM: [2] DUP AP: 
*WM: [2] DUP AP: 
*WM: [2] AP:  0 
*WM: [2] WiFi Scan ASYNC completed in 2347 ms
*WM: [2] WiFi Scan ASYNC found: 9
*WM: [3] lastconxresult: WL_IDLE_STATUS
*WM: [3] Sent config page 
*WM: [3] -> connectivitycheck.gstatic.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> connectivitycheck.gstatic.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [2] NUM CLIENTS: 1 
*WM: [3] -> connectivitycheck.gstatic.com 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> c.whatsapp.net 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> c.whatsapp.net 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> mini5.opera-mini.net 
*WM: [2] <- Request redirected to captive portal 
*WM: [3] -> c.whatsapp.net 
*WM: [2] <- Request redirected to captive portal 
*WM: [2] NUM CLIENTS: 1 
*WM: [2] <- HTTP WiFi save  
*WM: [3] Method: POST
*WM: [2] Parameters 
*WM: [2] -------------------- 
*WM: [2] str: hello
*WM: [2] float: 0.20
*WM: [2] int: 3
*WM: [2] ip: 1.1.1.1
*WM: [2] -------------------- 
*WM: [3] static ip: 1.1.1.1
*WM: [3] Sent wifi save page 
*WM: [2] process connect 
*WM: [2] Connecting as wifi client... 
*WM: [2] Custom STA IP/GW/Subnet 
*WM: [0] [ERROR] wifi config failed 
*WM: [3] WIFI station disconnect 
*WM: [1] Connecting to new AP: don
*WM: [3] WiFi station enable 
*WM: [3] enableSTA PERSISTENT ON 
*WM: [1] connectTimeout not set, ESP waitForConnectResult... 
*WM: [2] Connection result: WL_CONNECTED
*WM: [3] lastconxresult: WL_CONNECTED
*WM: [1] Connect to new AP [SUCCESS] 
*WM: [1] Got IP Address: 
*WM: [1] 192.168.1.51 
*WM: [2] disconnect configportal 
*WM: [2] restoring usermode STA+AP
*WM: [2] wifi status: WL_CONNECTED
*WM: [2] wifi mode: STA+AP
*WM: [1] config portal exiting 
String param: hello
Float param: 0.20
Int param: 3
IP param: 1.1.1.1
Settings saved
*WM: [3] freeing allocated params! 
*WM: [3] unloading 

* * * RESET * * *

␒�␄��8���Press setup button
3..2..1..Settings loaded
WORK
String param: hello
Float param: 0.20
Int param: 3
IP param: 1.1.1.1
```

**Comment by dontsovcmc** [comment]
wow. i never try =). yes, you are right.

**Comment by dontsovcmc** [comment]
Here is example: https://github.com/tzapu/WiFiManager/blob/development/examples/ParamsChildClass/ParamsChildClass.ino

**Pull request merged**
