### PR TITLE
Added Github Action to Compile Examples on ESP8266

### PR DESCRIPTION
**Pull request by shafr**
Hi, I've added compilation of all examples, so you would see if something would fail here in Github.
There are few tests failing - not sure what version of ArduinoJson it should be using - latest 6 fails with missing methods.

Please squash while merging.

### CODE REVIEW

**Comment by tablatronix** [comment]
Yeah there is an example that needs to be updated I think I just need to copy it over from hotfixes or a pr

**Comment by tablatronix** [comment]
Thanks , I will try to clean up examples, need to add esp32

**Comment by saikek** [comment]
Will add ESP32, ok

**Comment by tablatronix** [comment]
Thanks all , travis is down (migrate to .com required) I do not have repo access to migrate it, so this will be useful. I will fix the arduinojson example and just remove 5.x entirelty.

**Comment by tablatronix** [comment]
- add pull_request ?
- add branches filter (master)

to trigger

**Comment by tablatronix** [comment]
Thanks I will look it over and rework as needed, I will be cleaning up examples anyway for a beta release soon

**Pull request merged**
