### PR TITLE
Merge changes from master into feature_asyncwebserver

### PR DESCRIPTION
**Pull request by thorrak**
This PR brings the changes to date from master into the feature_asyncwebserver branch.

### CODE REVIEW

**Comment by tablatronix** [comment]
Did you rebase this, or did you have to fix all the conflicts?

**Comment by thorrak** [comment]
Rebasing it probably _would_ have been the smarter option...

I did this as a merge, and just fixed the various conflicts. End result works, though! (at least with asyncwebserver)

**Comment by tablatronix** [comment]
I need to figure out how to make this cross compatbile, maybe add a template as args to all these handlers, so it can be nulled for non async... hmm

**Comment by tablatronix** [comment]
I just remerged on my own and resolved, I needed to refresh my memory as to the changes so I can try to consolidate them into master cleanly

**Pull request closed without merging**
