### PR TITLE
Move WiFiManagerParameter to use a smart pointer and add copy/move constructors

### PR DESCRIPTION
**Pull request by axlan**
This is to address https://github.com/tzapu/WiFiManager/issues/1341 and https://github.com/tzapu/WiFiManager/issues/1050

These changes should have no affect on the functionality except to slightly simplify the class, and add the additional copy/move functions.

Feel free to use this as a starting point if there are stylistic inconsistencies.

### CODE REVIEW

**Comment by tablatronix** [comment]
There was a failed check, I merged anyway into new branch

```
/Users/shawn/projects/microcontrollers/dev/libraries/WiFiManager/WiFiManager.cpp:83:13: error: 'make_unique' is not a member of 'std'
   _value  = std::make_unique<char[]>(_length + 1);
             ^
/Users/shawn/projects/microcontrollers/dev/libraries/WiFiManager/WiFiManager.cpp:83:30: error: expected primary-expression before 'char'
   _value  = std::make_unique<char[]>(_length + 1);
                              ^
```

**Comment by tablatronix** [comment]
- [ ] fix make_unique for C++11

**Comment by tablatronix** [comment]
Do you know a better way to rewrite this, or add an overload for make_unique, it looks pretty easy from what I read

**Comment by axlan** [comment]
You can replace:
` _value  = std::make_unique<char[]>(_length + 1);`
with
 ` _value  = std::unique_ptr<char[]>(new char[_length + 1]);`

They're basically identical.

**Comment by tablatronix** [comment]
So wait now that these are smartpointers we can probably better determine when they are out of scope right?

this is what i have in there now

```cpp

    for (int i = 0; i < _paramsCount; i++) {
      Serial.println((String)_params[i]->_length);
      if (_params[i] == NULL || _params[i]->_length == 0 || _params[i]->_length > 99999) {
        // try to detect param scope issues, doesnt always catch but works ok
        #ifdef WM_DEBUG_LEVEL
        DEBUG_WM(DEBUG_ERROR,F("[ERROR] WiFiManagerParameter is out of scope"));
        #endif
        return "";
      }
    }
```

**Comment by axlan** [comment]
If I understand what you're asking correctly, you want to detect when the external code lets its allocation for `params_` deallocate (go out of scope or explicitly delete).

The smart pointer I added her only manages  `WiFiManagerParameter::_value`. Basically, just automatically frees the memory whenever _value would be over ridden or the parent is deconstructed. It doesn't affect the management of pointers of `WiFiManagerParameter`.

If you want that to be managed with smart pointers you'd need the user to pass in a smart pointer (shared, or unique depending on how you want the ownership to work). I can make a PR that implements that as well, but at some point I guess it might be easier to copy the `WiFiManagerParameter` into an internal allocation instead of making the user allocate space for them. This is potentially more expensive (need to spend CPU cycles for the copy, and not let the user specify where the memory is allocated), but it would do a lot to simplify how these parameters are specified. I'll make a version of this later since I think it would be preferable to expecting the library user to directly deal with smart pointers.

**Comment by tablatronix** [comment]
Well what alot of people do, is put the wm obj or params in setup, then if they try to do an ondemand in loop etc. It crashes.

Obviously this is because of how parameters are passed into the param class, and most folks just dont understand that much.or why their code crashes, I probably should see about adding compiler warnings also to reduce support issues

**Comment by tablatronix** [comment]
Well I have on my roadmap to make the whole setup of params as you have, allow them to be containerized and looped, or even stored in a main struct that is mapped into fs back and fort easily.

**Pull request merged**
