### PR TITLE
Added custom static DNS

### PR DESCRIPTION
**Pull request by debsahu**
Used vim in linux to edit the files. Hopefully didnt create a mess.

### CODE REVIEW

**Comment by tablatronix** [comment]
I had free time so i fixed it, already merged, thanks

**Comment by debsahu** [comment]
lol, thanks :}

**Comment by tablatronix** [comment]
I did change it to always show on webpage though, if showstaticfields is on

**Comment by debsahu** [comment]
learning to use github effectively, still a learning from googling.

**Comment by tablatronix** [comment]
check out core.autocrlf = auto, it keeps whitespaces same as repo

**Comment by debsahu** [comment]
So if the user only specifies ip, gw and sn, then the DNS will still pop up in the web interface. That's why I set it as optional, else we got to edit the readme that DNS is mandatory.

**Comment by tablatronix** [comment]
Why would it be mandatory, it can be blank, the problem is showststicfields and if staticipmare tied togsther, i might add a more detailed customization option to flag each one regardless of custom or not

**Comment by tablatronix** [comment]
Showstaticfields ip,gw,sn,dns bool, or maybe three state int 0,1,2 show always, show if set, show never

**Comment by tablatronix** [comment]
Maybe just 2 toggles, ip and dns, if you enable staticip you probsbly always want gw and sn also always

**Comment by debsahu** [comment]
Exactly, starting with and without dns.

**Pull request closed without merging**
