### PR TITLE
Fix travis builds, add esp32 builds

### PR DESCRIPTION
**Pull request by liebman**
Use current arduino version in builds.
Add esp32 platform builds excluding two examples due to SPIFFS incompatibility:
 - "AutoConnectWithFSParametersAndCustomIP.ino"
 - "AutoConnectWithFSParameters.ino"

Disabled the "codecov.io" support as no coverage is generated.

### CODE REVIEW

**Comment by liebman** [comment]
That's odd, this ran correctly on my fork!  I'll make a small change to try again.

**Comment by tablatronix** [comment]
I am not to hip on the travis, asking tzapu to sign off on this.
Looks good to me

**Comment by tablatronix** [comment]
Sorry about that I forgot to push

**Comment by liebman** [comment]
Passed!!!!

**Comment by tablatronix** [comment]
Thats what happens when you code while watching youtube...

**Comment by tablatronix** [comment]
#531 
#570

**Comment by tablatronix** [comment]
fix esp32 examples
7279333a179f13e62b6592701ea36a3d87bee79d

**Pull request merged**
