### PR TITLE
Allow showing static IP config without predefined value

### PR DESCRIPTION
**Pull request by vyruz1986**
Previously a valid predefined static IP had to be passed before the
config page would show the IP, gateway and subnet fields. This did not
allow the config page to show 'optional' static IP fields.
Now a boolean can be passed to the autoConnect() function which will
specify whether the static IP fields should be shown or not.
When this boolean is true but no predefined values are passed and fields
are left blank in config page, wifiManager will revert to DHCP. This
allows user to choose between static IP or DHCP without changing code

For backwards compatibility we will show the static IP fields regardless of how the boolean is set.

### CODE REVIEW

**Comment by tablatronix** [comment]
I think the argument should be dropped, and replaced with a setter for this option. We probably do not want to clog up the argument list with flags or options.

**Comment by vyruz1986** [comment]
That makes sense to me, are you going to implement this or do you want me to do it?

**Comment by tablatronix** [comment]
I can tweak it after pulling it in

**Comment by tablatronix** [comment]
hmm ill have to cherry pick it into development

**Comment by tablatronix** [comment]
oh nm you can now do it from the web !

**Pull request merged**
