### PR TITLE
Fix custom html from out of scope

### PR DESCRIPTION
**Pull request by liebman**
Over eager "parameter out of scope" check:
Custom html was triggering "parameter out of scope" as its length was 0 causing parameters not to be added.  In my case I have a "label" (custom html) first and none of my 31 parameters were showing up.

### CODE REVIEW

**Comment by liebman** [comment]
I think this should fix #678

**Comment by tablatronix** [comment]
Thanks I was just about to look at this. I did not realize people were using custom html like this, its not reallly ideal.

**Comment by liebman** [comment]
Yea, with 31 parameters I needed something to divide it into sections.

**Comment by tablatronix** [comment]
So using a empty param and injecting custom html to insert arbitrary html sections?

Ill add an example for this so I can make sure I dont break it. Then maybe next release we can deprecate it and add some better way to insert html components. Or maybe each param can be a component with a callout or something, this would reduce memory on the stack.

**Comment by liebman** [comment]
Basically this:
```
WiFiManagerParameter* section1 = new WiFiManagerParameter("<p>OTA Update</p>");
wm.addParameter(section1);
```

But I've put togeather a wrapper with callbacks for changed values and I add them all to a vector  to make it easier to manage its lifecycle:

```
    snprintf_P(message, sizeof(message), PSTR("<p>ESP: %s ATTiny: %u</p>"), SYNCHRO_CLOCK_VERSION, version);
    params.push_back(std::make_shared<ConfigParam>(wifi, message));

    params.push_back(std::make_shared<ConfigParam>(wifi, "position", "Clock Position", pos_str, 10, [](const char* result)
    {
        if (strlen(result))
        {
            uint16_t position = TimeUtils::parsePosition(result);
            dlog.info(FPSTR(TAG), F("setting position to %d"), position);
            if (clk.writePosition(position))
            {
                dlog.error(FPSTR(TAG), F("failed to set initial position!"));
            }
        }
    }));
    params.push_back(std::make_shared<ConfigParam>(wifi, "ntp_server", "NTP Server", config.ntp_server, 32, [](const char* result)
    {
            strncpy(config.ntp_server, result, sizeof(config.ntp_server) - 1);
    }));

    params.push_back(std::make_shared<ConfigParam>(wifi, "<p>OTA Update</p>"));
    params.push_back(std::make_shared<ConfigParam>(wifi, "ota_url", "OTA URL", getOTAurl(), 127, [](const char* result)
    {
        setOTAurl(result);
    }));
    params.push_back(std::make_shared<ConfigParam>(wifi, "ota_fp", "OTA fingerprint", getOTAfp(), 127, [](const char* result)
    {
        setOTAfp(result);
    }));
```

I'd love for this to be all handled internally with an interface like:
```
    wm.addParameter("ota_url", "OTA URL", getOTAurl(), 127, [](const char* result)
    {
        setOTAurl(result);
    }));
```
or something similar where there are callbacks for value changes or optionally the callback is called when when its not changed.

**Comment by tablatronix** [comment]
I believe I fixed this, this PR can probably be closed.

**Pull request closed without merging**
