### PR TITLE
Add HTTP Digest Authentication

### PR DESCRIPTION
**Pull request by PotatoCider**
This PR adds HTTP Digest Authentication (or revives the dead feature). May not work with some Android native webview browsers (Upon tapping "Sign in to network" notifications).

### CODE REVIEW

**Comment by Laxilef** [comment]
This is what is sorely missing right now.
I hope this PR will be merged.

**Comment by tablatronix** [comment]
Yes! How much testing have you done?

**Comment by PotatoCider** [comment]
I'm using this feature currently in a smart door lock, it works well for my use case. So far I've not encountered any bugs other than the captive portal not supporting HTTP auth prompts so a regular web browser would be required to login.

**Comment by tablatronix** [comment]
- [ ] Breaks captive portal detection OSX, how can we add options here
- [ ] Add ability for auth to select pages, OTA, ERASE

**Comment by Laxilef** [comment]
> Add ability for auth to select pages, OTA, ERASE

I don't think this is necessary. This will be confusing.
After all, we can dynamically turn authentication on and off in code.

> Breaks captive portal detections, how can we add options here, can we omit root perhaps, or add an auth  splash page

I see in the library code that the captivePortal() method is called before the handleRequest() method, so this should not affect the operation of the captive portal.

Also, I think captive portal should be disabled for WebPortal because it breaks port forwarding. In my projects I solved it like this:
```c++
      if (wm.getWebPortalActive()) {
        wm.setCaptivePortalEnable(false);
      }
```

**Comment by tablatronix** [comment]
That is already another issue, #982

**Comment by Laxilef** [comment]
> Good point about cp on webportal, surpised this hasnt been noticed before, how does it break port forwarding, got a test case?

You can flash any sketch and try to forward port 8181 -> 80 through the router. This can also be easily checked using the wokwi emulator.
I noticed this by chance when one of the users encountered a problem and I asked him to provide access to the ESP.
When I opened IP:8181, a redirect (302) to IP:80 occurred.
https://github.com/tzapu/WiFiManager/blob/18145e42ba686f297d4e741fb8805dffcb99a920/WiFiManager.cpp#L2451

**Comment by Laxilef** [comment]
> I gave up on this previously #1044, as it also did not work with cp at all on OSX/IOS devices, there is no auth in the cp browser

But how? Authorization is requested after processing the CP:
```c++
  if (captivePortal()) return; // If captive portal redirect instead of displaying the page
  if (!handleRequest()) return;
```

I'll check this in a couple of days.

**Comment by tablatronix** [comment]
CaptivePortal() is just a redirect, so it goes to handleroot / which is auth and an invalid response for the cp browser.

I was looking at the port code yeah we are not checking host port from header, that might be fixable, but makes sense to just to skip cp checks entirely in not on ap.. since its irrelevant

**Comment by tablatronix** [comment]
I never addressed this because its dumb, it would be worth implementing basic html auth instead to protect in ap/cp mode.

**Pull request merged**
