### PR TITLE
Move more strings to FLASH to free up RAM

### PR DESCRIPTION
**Pull request by horendus**
Place remaining debug messages into Flash using F() and declare a few other strings with F()

### CODE REVIEW

**Comment by horendus** [comment]
No sure why this is pull request is failing check, very basic changes. Most debug messages already using F() however are few were missing it, eating up extra RAM.

**Comment by tablatronix** [comment]
Thanks but all development is being done in development branch. I probably wont merge, I also plan on moving all debug strings to progmem and wrapping in precompiler ifdefs so they wont be compiled at all if needed.

**Comment by horendus** [comment]
Ok, well no worries well ESP8266 core is making a big effort to free up RAM on the heap and as this is one of the best libraries for use with the ESP8266 it would make sense so also go in that direction. I had a look at the development branch last night but found it used significantly more RAM than the Master. What are the main changes / additions in the Dev branch? I could go over all the pull requests but if you dont mind just listing them thats would be great!

**Comment by tablatronix** [comment]
Just look at the PR, it has all the development.
I have not done memory evaluation yet, do you have stats? I will probably work on that soon

**Comment by tablatronix** [comment]
I just reworked a bunch of strings

#518

**Pull request merged**
