### PR TITLE
fix potential memory leak in  WiFiManagerParameter::setValue

### PR DESCRIPTION
**Pull request by cpainchaud**

### CODE REVIEW

**Comment by tablatronix** [comment]
So this would address a memory leak when calling setValue multiple times with changing values, correct?

**Comment by cpainchaud** [comment]
I think so

**Comment by tablatronix** [comment]
I need reviewers lol, ill try to look at this when i get a chance

**Comment by tablatronix** [comment]
reverted, crashes esp32

bad array access

assertion "heap != NULL && "free() target pointer is outside heap areas"

**Comment by tablatronix** [comment]
@cpainchaud I had to revert this it was crashing esp32

**Comment by cpainchaud** [comment]
I saw that, it's weird actually, it means that another part of the code is relying on that memory to never be freed while it's obviously leaked ....

**Comment by tablatronix** [comment]
yeah I did not really look at it at all, was busy on stuff. it crashed immediately also which is odd..

**Comment by hurricanefrog** [comment]
This is because _value is not initialized in the constructor, or rather the `init` function - meaning the pointer is random.

Simply do `_value = nullptr;` in `init` and it's fixed

**Comment by tablatronix** [comment]
I think this is right, please check

**Comment by hurricanefrog** [comment]
Works fine, doesn't crash

**Comment by hurricanefrog** [comment]
> Works fine, doesn't crash

Or maybe it does? Just re-tested this. Initial flash goes fine, but if I OTA update "my" application again, I get a `StoreProhibited` error. Need to check where exactly, though

**Comment by hurricanefrog** [comment]
I think this is because `_length` is uninitialized as well! So `if(_length != length)` yields random results

**Comment by tablatronix** [comment]
Thanks for testing this, let me know what you find or if you do not, etc

**Comment by zenz** [comment]
on ESP8266, this
delete[] _value;
_value = new char[....]
will cause a crash.
So I use unique_ptr to try to solve the issue.
And I make a pull request, please check.

**Comment by tablatronix** [comment]
Thanks, I havent had time to really look at this, and I am pretty sure I left a mic of null and nullptr in here, It need to be reworked to be memory safe, and I was just trying to figure out how make this safer when these are out of scope ( which alot of people do ) and make it not crash

**Pull request merged**
