### PR TITLE
 add CORS headers

### PR DESCRIPTION
**Pull request by ohadcn**
this will allow external portal on the network to send credentials via browser.

### CODE REVIEW

**Comment by tablatronix** [comment]
Should we make this optional or allow passing in parameters for source and access control ?

**Comment by ohadcn** [comment]
in the rare case of someone connected to WiFiManager while browsing websites on internet this could be a security issue - as the website might send ESP wrong wifi credentials and make it useless.
except this rare case I see no reason to disable it.

but we can add it as parameter.

**Comment by tablatronix** [comment]
Yeah it would be a very specific xss attack but who knows.

**Comment by cbh6** [comment]
Any info about when will this be released ?

Thanks

**Pull request merged**
