### PR TITLE
make `connectWifi` public method

### PR DESCRIPTION
**Pull request by TRANTANKHOA**
I'm using some default ssid and password that I want to try first before triggering the auto-connect workflow.

### CODE REVIEW

**Comment by tablatronix** [comment]
Just use begin and check wifi status or waitforconnectresult, i would stick with esp functions for that

**Comment by TRANTANKHOA** [comment]
But this built in function can set static IP too. Is there a consequence of making it public?

**Comment by tablatronix** [comment]
It is not a public method

**Comment by tablatronix** [comment]
you can do autoconnect with configportal disabled

**Pull request closed without merging**
