### PR TITLE
Two examples ArduinoJson 6 compatibility changes

### PR DESCRIPTION
**Pull request by bigjohnson**
Changed two examples code for ArduinoJson 6 library usage.

### CODE REVIEW

**Comment by Ruandv** [comment]
is there any reason why this is not merged into master yet?
These changes would be very handy for new users

**Comment by tablatronix** [comment]
I have not tested it

**Comment by tablatronix** [comment]
are you signing off on it ? Have you tested it?

**Comment by Ruandv** [comment]
I will test it tonight on my device and give you a final confirmation. I had a scan over the code the day i was looking for a sample and mine ended up the similar to this.

**Comment by Ruandv** [comment]
@tablatronix  pull request is not relevant anymore because of pull request #993

**Pull request closed without merging**
