### PR TITLE
Add label to the "show password" checkbox

### PR DESCRIPTION
**Pull request by skorokithakis**
This ensures that tapping the text toggles the checkbox.

### CODE REVIEW

**Comment by Bighoneypot** [comment]
image

**Comment by dontsovcmc** [comment]
@skorokithakis i think you should add function f() to script page text

**Comment by skorokithakis** [comment]
@dontsovcmc Why is that? I didn't change that.

**Comment by dontsovcmc** [comment]
> @dontsovcmc Why is that? I didn't change that.

sorry. i think you add checkbox... you add only label.

**Comment by skorokithakis** [comment]
@dontsovcmc I only added the `<label>` element around what was already there, I didn't change the checkbox code.

**Comment by tablatronix** [comment]
@dontsovcmc what do you mean? Is something missing , checkbox was added recently

**Comment by skorokithakis** [comment]
Sorry guys, this is a 10-byte PR that has been left unmerged since February. It has taken more of our collective time discussing this than someone just writing `<label>` in the code, and the PR itself has rotted, so I'll just close it. Thank you all for your time.

**Pull request closed without merging**
