### PR TITLE
WIP: Added OTA updater option from esp8266

### PR DESCRIPTION
**Pull request by sidey79**
Added OTA update support in config portal page

### CODE REVIEW

**Comment by sidey79** [comment]
@tablatronix 
I Would like to know, if this is a feature you are willing to merge, before i put more work on it.
Otherwise, i can also provide an additional class which is a parent from your class.

**Comment by tablatronix** [comment]
I doubt it needs to be in core. Unless its very lightweight

**Comment by tablatronix** [comment]
I thought about refactoring menu and routes, so you can easily add menuoptions and routes, with callouts then you can just add this stuff fairly easily without modifying the lib.

**Comment by sidey79** [comment]
The libs needed seems to be already included per default in esp8266 core.

But there are some additional strings needed for the pages. Not sure if this is lightweight enough.

If you provide callbacks i could separate the update stuff in another class. But it would need some access to the server object.

**Comment by tablatronix** [comment]
#461

**Comment by sidey79** [comment]
In general, the pull request works on eps8266. But i haven't tested it on an ESP32.

Im also not sure, what breaks the example tests.

**Comment by liebman** [comment]
This is the error:

```
In file included from /home/travis/build/tzapu/WiFiManager/examples/AutoConnectWithStaticIP/AutoConnectWithStaticIP.ino:2:0:
/usr/local/share/arduino/libraries/WiFiManager/WiFiManager.h:46:25: fatal error: Updater.h: No such file or directory
```
Maybe that does not exist for the esp32 or has a different name?

**Comment by sidey79** [comment]
I can't believe it...

https://github.com/espressif/arduino-esp32/tree/master/libraries/Update/src

`
Update.h	
Updater.cpp
`

**Comment by liebman** [comment]
You should install the esp32 Arduino and test compile as there are some class differences.....

```
/usr/local/share/arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'void WiFiManager::handleUpdating()':
/usr/local/share/arduino/libraries/WiFiManager/WiFiManager.cpp:2419:3: error: 'stopAll' is not a member of 'WiFiUDP'
   WiFiUDP::stopAll();
   ^
/usr/local/share/arduino/libraries/WiFiManager/WiFiManager.cpp:2421:34: error: 'class EspClass' has no member named 'getFreeSketchSpace'
   uint32_t maxSketchSpace = (ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000;
                                  ^
```

**Comment by tablatronix** [comment]
I would file that as a bug with esp232 m thats messed up

**Comment by tablatronix** [comment]
Merged into ota branch for testing.
i had to fix your urls they were backwards and didnt work.

I an probably going to pull this out into an example with user code insread of core, but this is working and testable, I added todos to code

**Comment by tablatronix** [comment]
you need to fix your strings menu_ids it is missing the update token `_nummenutokens` index must match HTTP_PORTAL_MENU index

**Comment by tablatronix** [comment]
https://github.com/tzapu/WiFiManager/commit/3e2f8ae9d81badcf00ca8d2c2cb8cb4c205e9cc1

**Comment by sidey79** [comment]
sorry, i forgot to check this

**Comment by sidey79** [comment]
I'm not sure what ist open to geht this also in the Development branch.

One thing which ist absolutely a must ist a paaaword protection i think.

**Comment by tablatronix** [comment]
There is an ota branch for this, it works

**Comment by tablatronix** [comment]
it has not been tested well and probably needs some minor improvements

**Pull request merged**
