### PR TITLE
Feature 308 configportaltimeouts

### PR DESCRIPTION
**Pull request by tablatronix**

### CODE REVIEW

**Comment by tzapu** [comment]
thanks for this, 
if i read it correctly ,will this exit the flow as soon as the connected party disconnects?
would it be more intuitive to reset the timeout if someone is connected? or make it longer?
just thinking outloud, but if you connect with your phone, then decide to use your laptop to configure, disconnect from phone, it will probably restart by the time you connect with the laptop.
although, not sure i read it right

cheers

**Comment by tablatronix** [comment]
If the timeout was set and has exceeded, yes. Right now it timesout when you are using the portal which is not great.

If a webclient timeout is required, then I think it should be a seperate feature, with a bumped timestamp on every request. I thought about using configportalstarttime but that seemed hacky we would want a new timestamp configportallastactivity for example, so decided it should be 2 seperate things, as the later requires new functionality and globals. And there is some decisions to be made about how that would work as it could also timeout when you are still typing in configuration forms etc.

**Comment by tablatronix** [comment]
note, I updated comment in case you are using email...

**Comment by tablatronix** [comment]
I reopened #308 to discuss, since this might cause unexpected changes

**Pull request merged**
