### PR TITLE
Fix ArduinoJson (Using ARDUINOJSON_VERSION_MAJOR)

### PR DESCRIPTION
**Pull request by Ruandv**
This is relates to the ArduinoJson 5 / 6 changes.
I took what @bigjohnson did in a502456 and just added a #define UseJsonV6 option that can be commented out if you want to use ArduinoJsonV5.
Tested on ArduinoJson V 5.13 and ArduinoJson V 6.13 (Latest as at 14/01/2020)

This also links to #654 and #812 
- [x] update examples to be compatible with future arduinojson library
- [x] Maybe add support in the example in question for both versioons somehow?
- [x] Can also Close #945

### CODE REVIEW

**Comment by bigjohnson** [comment]
Perfect, but I think is better automate it replacing
#ifdef UseJsonV6
with
#if ARDUINOJSON_VERSION_MAJOR >= 6

**Comment by Ruandv** [comment]
Ok good suggestion. Thank you I didn't know there is a way to do that. Will update it soon

**Comment by tablatronix** [comment]
I should have rebased this.. Should be ok

**Comment by tablatronix** [comment]
Compiles for me

**Comment by userweb2018** [comment]
For me too, but this is strange....
It is not working perfectly everytime!
In which way can I use it with ondemand with pushbuttom and parameters?

**Pull request merged**
