### PR TITLE
CI / DC Update - Library Build, Linting, Examples Json Fix

### PR DESCRIPTION
**Pull request by shafr**
**Updated:**
```
Examples compilation in one file. Using ArduinoJson v5 for now.
```

**Added**
```
Library building
Linting on pull request
```

### CODE REVIEW

**Comment by tablatronix** [comment]
This combines both platforms?

**Comment by shafr** [comment]
it has both esp8266 & esp32 library builds & example builds

**Comment by tablatronix** [comment]
Thanks!

**Comment by tablatronix** [comment]
merged and fixed up 
stupid question why are the boards reversed?

esp32:
        run: pio ci --board=nodemcuv2

**Comment by shafr** [comment]
yep, thats bug, please reverse

**Comment by tablatronix** [comment]
oddly it was working just fine

**Comment by shafr** [comment]
also you can check my 'canary' repo actions - i have one that calculates FW / disk usage for pull requests

**Comment by tablatronix** [comment]
interesting, I will check it out, I need to work on doxygen

**Comment by tablatronix** [comment]
looks like we have a mix of yml and yaml, which one is best more standard?
I always use .yaml

**Comment by shafr** [comment]
There's no rule, probably I was not paying attention, I prefer using shortest one.

**Pull request merged**
