### PR TITLE
Update WiFiManager.template.html

### PR DESCRIPTION
**Pull request by vishalroygeek**
Adding some CSS to make the template look better

### CODE REVIEW

**Comment by vishalroygeek** [comment]
@tzapu I have applied some cool CSS to make the configuration page to look great and have some feel. I am already using it in many of my projects. Those who want to apply the CSS on their existing project right now, can simply copy & paste the line below in their projects 😄

`  wifiManager.setCustomHeadElement("<style>body{background: #f7f5f5;}button{transition: 0.3s;opacity: 0.8;cursor: pointer;border:0;border-radius:1rem;background-color:#1dca79;color:#fff;line-height:2.4rem;font-size:1.2rem;width:100%;}button:hover {opacity: 1}button[type=\"submit\"]{margin-top: 15px;margin-bottom: 10px;font-weight: bold;text-transform: capitalize;}input{height: 30px;font-family:verdana;margin-top: 5px;background-color: rgb(253, 253, 253);border: 0px;-webkit-box-shadow: 2px 2px 5px 0px rgba(0,0,0,0.75);-moz-box-shadow: 2px 2px 5px 0px rgba(0,0,0,0.75);box-shadow: 2px 2px 5px 0px rgba(0,0,0,0.75);}div{color: #14a762;}div a{text-decoration: none;color: #14a762;}div[style*=\"text-align:left;\"]{color: black;}, div[class*=\"c\"]{border: 0px;}a[href*=\"wifi\"]{border: 2px solid #1dca79;text-decoration: none;color: #1dca79;padding: 10px 30px 10px 30px;font-family: verdana;font-weight: bolder;transition: 0.3s;border-radius: 5rem;}a[href*=\"wifi\"]:hover{background: #1dca79;color: white;}</style>");
`

**Comment by tablatronix** [comment]
Screenshot please

**Comment by vishalroygeek** [comment]
Sure. You can check the screenshot here - 

https://github.com/vishalroygeek/WiFiManager/blob/master/extras/HTML%20Template%20Screenshot.png

**Comment by tablatronix** [comment]
Ill take a look and see what exactly the changes are, I have already implemented some style updates in development branch

**Pull request closed without merging**
