### PR TITLE
It can show connect ip at the bottom of root page after wifi config.

### PR DESCRIPTION
**Pull request by bibo19842003**
It can show ESP IP after wifi config, but it needs click 'reset' button on the root page for restart after wifi config.

涂鸦_Screenshot_2020-12-15-13-49-30-356

涂鸦_Screenshot_2020-12-15-13-49-39-249

涂鸦_Screenshot_2020-12-15-13-49-52-008

### CODE REVIEW

**Comment by tablatronix** [comment]
The dev branch already shows this information

**Comment by bibo19842003** [comment]
@tablatronix 
1. I had found many branches in wifimanager project , where i can find the relationship between these branches.
2. development branch is 704 commits ahead, 34 commits behind master. we use development branch and no longer use master branch in future?

Thank you.

**Comment by tablatronix** [comment]
#580

**Comment by tablatronix** [comment]
It says it on the readme
https://github.com/tzapu/WiFiManager

**Comment by bibo19842003** [comment]
got it , thank you

**Pull request closed without merging**
