### PR TITLE
fix compiler warnings

### PR DESCRIPTION
**Pull request by liebman**
Fixed a few compiler warnings.

### CODE REVIEW

**Comment by liebman** [comment]
` -Wall -Wextra`  and I wish the Arduino IDE used those but it only uses `-w` (see: https://github.com/arduino/Arduino/issues/4184).   I'm using Eclipse with the Sloeber plugin as that gives me a much more complete IDE. 

And I'll look into why travis is failing....  if I find it I'll submit a separate PR.

**Comment by tablatronix** [comment]
hmm I use those flags, and do not get unsigned warnings.

**Comment by liebman** [comment]
From the tzapu/WiFiManager:development branch:

```
Building file: /Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp
Starting C++ compile
"/Users/chris.l/Arduino/hardware/esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/chris.l/Arduino/hardware/esp8266/tools/sdk/include" "-I/Users/chris.l/Arduino/hardware/esp8266/tools/sdk/lwip2/include" "-I/Users/chris.l/Arduino/hardware/esp8266/tools/sdk/libc/xtensa-lx106-elf/include" "-I/Users/chris.l/eclipse-workspace/WMTest/Release/core" -c -Wall -Wextra -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_CORE -DARDUINO=10802 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 '-DARDUINO_BOARD="ESP8266_NODEMCU"'  -DESP8266  -I"/Users/chris.l/Arduino/hardware/esp8266/cores/esp8266" -I"/Users/chris.l/Arduino/hardware/esp8266/variants/nodemcu" -I"/Users/chris.l/Arduino/hardware/esp8266/libraries/DNSServer/src" -I"/Users/chris.l/Arduino/hardware/esp8266/libraries/ESP8266WebServer/src" -I"/Users/chris.l/Arduino/libraries/WiFiManager" -I"/Users/chris.l/Arduino/hardware/esp8266/libraries/ESP8266WiFi/src" -MMD -MP -MF"libraries/WiFiManager/WiFiManager.cpp.d" -MT"libraries/WiFiManager/WiFiManager.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp"  -o  "libraries/WiFiManager/WiFiManager.cpp.o"
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'bool WiFiManager::addParameter(WiFiManagerParameter*)':
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp:102:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < strlen(p->getID()); i++){
                                          ^
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'uint8_t WiFiManager::waitForConnectResult()':
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp:691:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while(millis() < timeout) {
                    ^
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'bool WiFiManager::WiFi_scanNetworks(int)':
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp:837:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     return WiFi_scanNetworks(millis()-_lastscan > cachetime);
                                                   ^
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp: At global scope:
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp:1615:6: warning: unused parameter 'opt' [-Wunused-parameter]
 bool WiFiManager::erase(bool opt){
      ^
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp:1885:6: warning: unused parameter 'enabled' [-Wunused-parameter]
 void WiFiManager::setScanDispPerc(boolean enabled){
      ^
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'void WiFiManager::setMenu(WiFiManager::menu_page_t*, uint8_t)':
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp:1919:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(i=0;i<sizeof(_menuIds);i++){
                            ^
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp:1921:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(i >= n) _menuIds[i] = MENU_END;
               ^
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'bool WiFiManager::WiFi_Disconnect()':
/Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp:2159:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Finished building: /Users/chris.l/Arduino/libraries/WiFiManager/WiFiManager.cpp
 ```

**Comment by tablatronix** [comment]
Yeah i cant seem to get my compiler to complain about those, that is what I am guessing it was.
hmm

**Comment by tablatronix** [comment]
I just commited some changes for some datatypes

**Comment by tablatronix** [comment]
I got it now, for some reason esp32 does not throw these

**Comment by tablatronix** [comment]
fixed em all

do you know why this is

` const char * const _menutokens[9] PROGMEM = {`
` error: section attribute not allowed for '_menutokens'`
It only complains when its in the main.h but not an include...

**Comment by tablatronix** [comment]
oh duh, nevermind

**Pull request closed without merging**
