### PR TITLE
@PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by ivankravets**
* This library in Web Registry: http://platformio.org/#!/lib/show/567/WifiManager
* Specification: [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html)
* Library Manager:  http://docs.platformio.org/en/latest/librarymanager/index.html

### CODE REVIEW

**Comment by doom369** [comment]
@ivankravets I just was thinking to write to you about it =).

**Comment by ivankravets** [comment]
@doom369 I've just received request from user as for this lib :)

P.S: Do you use @PlatformIO for building/uploading for @blynkkk?

**Comment by doom369** [comment]
Not at the moment. @PlatformIO in my todo list.

**Comment by ivankravets** [comment]
@doom369 Thanks! :+1:

**Pull request merged**
